create table if not exists public.degul_event (
  event_id uuid primary key default gen_random_uuid(),
  title text not null,
  application_open_at timestamptz,
  application_deadline_at timestamptz not null,
  event_at timestamptz not null,
  location text not null,
  content text,
  created_by uuid not null references public.degul_users(id),
  use_yn char(1) not null default 'Y' check (use_yn in ('Y','N')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.degul_event_image (
  image_id bigint generated by default as identity primary key,
  event_id uuid not null references public.degul_event(event_id) on delete cascade,
  file_name text not null,
  file_path text not null,
  sort_no integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.degul_event_participation (
  event_id uuid not null references public.degul_event(event_id) on delete cascade,
  user_id uuid not null references public.degul_users(id) on delete cascade,
  participation_status text not null check (participation_status in ('ATD','PND','ABS')),
  updated_at timestamptz not null default now(),
  primary key (event_id, user_id)
);

alter table public.degul_event enable row level security;
alter table public.degul_event_image enable row level security;
alter table public.degul_event_participation enable row level security;

drop policy if exists event_read_authenticated on public.degul_event;
create policy event_read_authenticated on public.degul_event for select to authenticated using (use_yn = 'Y');
drop policy if exists event_manage_staff on public.degul_event;
create policy event_manage_staff on public.degul_event for all to authenticated
using (exists (select 1 from public.degul_users u where u.id=auth.uid() and u.status='ACT' and u.role in ('ADM','MGR','STF')))
with check (exists (select 1 from public.degul_users u where u.id=auth.uid() and u.status='ACT' and u.role in ('ADM','MGR','STF')));

drop policy if exists event_image_read_authenticated on public.degul_event_image;
create policy event_image_read_authenticated on public.degul_event_image for select to authenticated using (true);
drop policy if exists event_image_manage_staff on public.degul_event_image;
create policy event_image_manage_staff on public.degul_event_image for all to authenticated
using (exists (select 1 from public.degul_users u where u.id=auth.uid() and u.status='ACT' and u.role in ('ADM','MGR','STF')))
with check (exists (select 1 from public.degul_users u where u.id=auth.uid() and u.status='ACT' and u.role in ('ADM','MGR','STF')));

drop policy if exists event_participation_read_authenticated on public.degul_event_participation;
create policy event_participation_read_authenticated on public.degul_event_participation for select to authenticated using (true);
drop policy if exists event_participation_write_own on public.degul_event_participation;
create policy event_participation_write_own on public.degul_event_participation for all to authenticated
using (user_id=auth.uid()) with check (user_id=auth.uid());

insert into storage.buckets (id, name, public)
values ('event', 'event', true) on conflict (id) do update set public=true;

drop policy if exists event_storage_read on storage.objects;
create policy event_storage_read on storage.objects for select using (bucket_id='event');
drop policy if exists event_storage_manage_staff on storage.objects;
create policy event_storage_manage_staff on storage.objects for all to authenticated
using (bucket_id='event' and exists (select 1 from public.degul_users u where u.id=auth.uid() and u.status='ACT' and u.role in ('ADM','MGR','STF')))
with check (bucket_id='event' and exists (select 1 from public.degul_users u where u.id=auth.uid() and u.status='ACT' and u.role in ('ADM','MGR','STF')));
