create table if not exists public.degul_capsule_coin_history (
  coin_history_id bigint generated by default as identity primary key,
  user_id uuid not null references public.degul_users(id),
  round_id bigint not null references public.degul_capsule_round(round_id),
  meeting_id uuid references public.degul_meeting(meeting_id),
  capsule_id bigint references public.degul_capsule(capsule_id),
  coin_tp varchar(10) not null,
  coin_qty integer not null,
  memo text,
  created_at timestamptz not null default now(),
  created_by uuid references public.degul_users(id),

  constraint chk_capsule_coin_tp
    check (coin_tp in ('ATD', 'DRAW', 'ADMIN', 'CANCEL')),
  constraint chk_capsule_coin_qty
    check (coin_qty <> 0),
  constraint chk_capsule_coin_source
    check (
      (
        coin_tp = 'ATD'
        and coin_qty > 0
        and meeting_id is not null
        and capsule_id is null
      )
      or
      (
        coin_tp = 'DRAW'
        and coin_qty < 0
        and meeting_id is null
        and capsule_id is not null
      )
      or
      (
        coin_tp = 'ADMIN'
        and meeting_id is null
        and capsule_id is null
      )
      or
      (
        coin_tp = 'CANCEL'
        and coin_qty > 0
        and meeting_id is null
        and capsule_id is not null
      )
    )
);

comment on table public.degul_capsule_coin_history
  is '캡슐 이벤트 회차별 코인 지급 및 사용 원장';

comment on column public.degul_capsule_coin_history.coin_tp
  is 'ATD: 참석 지급, DRAW: 뽑기 사용, ADMIN: 관리자 조정, CANCEL: 뽑기 취소 복구';

create unique index if not exists uk_capsule_coin_attendance
  on public.degul_capsule_coin_history (user_id, round_id, meeting_id)
  where coin_tp = 'ATD';

create unique index if not exists uk_capsule_coin_draw
  on public.degul_capsule_coin_history (capsule_id)
  where coin_tp = 'DRAW';

create index if not exists idx_capsule_coin_user_round
  on public.degul_capsule_coin_history (user_id, round_id, created_at desc);

create index if not exists idx_capsule_coin_meeting
  on public.degul_capsule_coin_history (meeting_id)
  where meeting_id is not null;
